# Generated by Django 5.0.6 on 2024-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('phone_no', models.CharField(max_length=14)),
                ('salary', models.FloatField()),
                ('address', models.TextField()),
            ],
        ),
    ]
